// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

[Table("autor")]
public partial class Autor
{
    [Key]
    [Column("id_autor")]
    public int IdAutor { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [InverseProperty("IdAutorNavigation")]
    public virtual ICollection<Livro> Livro { get; set; } = new List<Livro>();
}