// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

[Table("biblioteca")]
public partial class Biblioteca
{
    [Key]
    [Column("id_biblioteca")]
    public int IdBiblioteca { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("endereco")]
    [StringLength(255)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [InverseProperty("BibliotecaNavigation")]
    public virtual ICollection<LivroBiblioteca> LivroBiblioteca { get; set; } = new List<LivroBiblioteca>();
}