// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

[Table("cliente")]
[Index("Email", Name = "UQ__cliente__AB6E616407A7B8AF", IsUnique = true)]
[Index("Cpf", Name = "UQ__cliente__D836E71F90420DBC", IsUnique = true)]
public partial class Cliente
{
    [Key]
    [Column("id_cliente")]
    public int IdCliente { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("email")]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("telefone")]
    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Column("cpf")]
    [StringLength(14)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Emprestimo> Emprestimo { get; set; } = new List<Emprestimo>();

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Multa> Multa { get; set; } = new List<Multa>();
}