// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

public partial class LibrarycContext : DbContext
{
    public LibrarycContext(DbContextOptions<LibrarycContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Autor> Autor { get; set; }

    public virtual DbSet<Biblioteca> Biblioteca { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Emprestimo> Emprestimo { get; set; }

    public virtual DbSet<Livro> Livro { get; set; }

    public virtual DbSet<LivroBiblioteca> LivroBiblioteca { get; set; }

    public virtual DbSet<Multa> Multa { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Autor>(entity =>
        {
            entity.HasKey(e => e.IdAutor).HasName("PK__autor__5FC3872DE7AFBC7E");
        });

        modelBuilder.Entity<Biblioteca>(entity =>
        {
            entity.HasKey(e => e.IdBiblioteca).HasName("PK__bibliote__1EEBBDFEAF780565");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__cliente__677F38F5662BD2FF");
        });

        modelBuilder.Entity<Emprestimo>(entity =>
        {
            entity.HasKey(e => e.IdEmprestimo).HasName("PK__empresti__45FD187E70A8E12D");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Emprestimo).HasConstraintName("FK__emprestim__id_cl__4D94879B");

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.Emprestimo).HasConstraintName("FK__emprestim__id_li__4E88ABD4");
        });

        modelBuilder.Entity<Livro>(entity =>
        {
            entity.HasKey(e => e.IdLivro).HasName("PK__livro__C252147D8E52CF6E");

            entity.HasOne(d => d.IdAutorNavigation).WithMany(p => p.Livro).HasConstraintName("FK__livro__id_autor__44FF419A");
        });

        modelBuilder.Entity<LivroBiblioteca>(entity =>
        {
            entity.HasKey(e => e.IdLivroBiblioteca).HasName("PK__livro_bi__C7822DFE973F5B82");

            entity.HasOne(d => d.BibliotecaNavigation).WithMany(p => p.LivroBiblioteca).HasConstraintName("FK__livro_bib__bibli__60A75C0F");

            entity.HasOne(d => d.LivroNavigation).WithMany(p => p.LivroBiblioteca).HasConstraintName("FK__livro_bib__livro__5FB337D6");
        });

        modelBuilder.Entity<Multa>(entity =>
        {
            entity.HasKey(e => e.IdMulta).HasName("PK__multa__295650BBA28E50D4");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Multa).HasConstraintName("FK__multa__id_client__403A8C7D");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__usuario__4E3E04AD2F600AEF");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}