// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

public partial class LibrarycContext : DbContext
{
    public LibrarycContext(DbContextOptions<LibrarycContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Autor> Autor { get; set; }

    public virtual DbSet<Biblioteca> Biblioteca { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Emprestimo> Emprestimo { get; set; }

    public virtual DbSet<Livro> Livro { get; set; }

    public virtual DbSet<LivroBiblioteca> LivroBiblioteca { get; set; }

    public virtual DbSet<Multa> Multa { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Autor>(entity =>
        {
            entity.HasKey(e => e.IdAutor).HasName("PK__autor__5FC3872DC301C732");
        });

        modelBuilder.Entity<Biblioteca>(entity =>
        {
            entity.HasKey(e => e.IdBiblioteca).HasName("PK__bibliote__1EEBBDFE281AC4B8");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__cliente__677F38F5CA8CA5A3");
        });

        modelBuilder.Entity<Emprestimo>(entity =>
        {
            entity.HasKey(e => e.IdEmprestimo).HasName("PK__empresti__45FD187E42C5A0B8");

            entity.HasOne(d => d.IdBibliotecaNavigation).WithMany(p => p.Emprestimo).HasConstraintName("FK__emprestim__id_bi__4D94879B");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Emprestimo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__emprestim__id_cl__4E88ABD4");

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.Emprestimo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__emprestim__id_li__4F7CD00D");
        });

        modelBuilder.Entity<Livro>(entity =>
        {
            entity.HasKey(e => e.IdLivro).HasName("PK__livro__C252147DF73055FC");

            entity.HasOne(d => d.IdAutorNavigation).WithMany(p => p.Livro).HasConstraintName("FK__livro__id_autor__46E78A0C");
        });

        modelBuilder.Entity<LivroBiblioteca>(entity =>
        {
            entity.HasKey(e => e.IdLivroBiblioteca).HasName("PK__livro_bi__C7822DFEA5F88D41");

            entity.HasOne(d => d.IdBibliotecaNavigation).WithMany(p => p.LivroBiblioteca).HasConstraintName("FK__livro_bib__id_bi__4AB81AF0");

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.LivroBiblioteca).HasConstraintName("FK__livro_bib__id_li__49C3F6B7");
        });

        modelBuilder.Entity<Multa>(entity =>
        {
            entity.HasKey(e => e.IdMulta).HasName("PK__multa__295650BB36BC9AE5");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Multa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__multa__id_client__4222D4EF");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__usuario__4E3E04AD8C3DEA94");

            entity.HasOne(d => d.IdBibliotecaNavigation).WithMany(p => p.Usuario).HasConstraintName("FK__usuario__id_bibl__3B75D760");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}