// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

[Table("livro")]
public partial class Livro
{
    [Key]
    [Column("id_livro")]
    public int IdLivro { get; set; }

    [Required]
    [Column("titulo")]
    [StringLength(255)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Column("ano_publicacao")]
    public int? AnoPublicacao { get; set; }

    [Column("id_autor")]
    public int? IdAutor { get; set; }

    [Column("quantidade")]
    public int Quantidade { get; set; }

    [InverseProperty("IdLivroNavigation")]
    public virtual ICollection<Emprestimo> Emprestimo { get; set; } = new List<Emprestimo>();

    [ForeignKey("IdAutor")]
    [InverseProperty("Livro")]
    public virtual Autor IdAutorNavigation { get; set; }
}