// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

[Table("livro_biblioteca")]
public partial class LivroBiblioteca
{
    [Key]
    [Column("id_livro_biblioteca")]
    public int IdLivroBiblioteca { get; set; }

    [Column("livro")]
    public int? Livro { get; set; }

    [Column("biblioteca")]
    public int? Biblioteca { get; set; }

    [Column("quantidade")]
    public int Quantidade { get; set; }

    [ForeignKey("Biblioteca")]
    [InverseProperty("LivroBiblioteca")]
    public virtual Biblioteca BibliotecaNavigation { get; set; }

    [ForeignKey("Livro")]
    [InverseProperty("LivroBiblioteca")]
    public virtual Livro LivroNavigation { get; set; }
}