// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

[Table("livro_biblioteca")]
public partial class LivroBiblioteca
{
    [Key]
    [Column("id_livro_biblioteca")]
    public int IdLivroBiblioteca { get; set; }

    [Column("id_livro")]
    public int? IdLivro { get; set; }

    [Column("id_biblioteca")]
    public int? IdBiblioteca { get; set; }

    [Column("quantidade")]
    public int Quantidade { get; set; }

    [ForeignKey("IdBiblioteca")]
    [InverseProperty("LivroBiblioteca")]
    public virtual Biblioteca IdBibliotecaNavigation { get; set; }

    [ForeignKey("IdLivro")]
    [InverseProperty("LivroBiblioteca")]
    public virtual Livro IdLivroNavigation { get; set; }
}