// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryC.Models;

[Table("usuario")]
[Index("Email", Name = "UQ__usuario__AB6E6164C431BFFF", IsUnique = true)]
[Index("Cpf", Name = "UQ__usuario__D836E71F34E4F432", IsUnique = true)]
public partial class Usuario
{
    [Key]
    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("email")]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("cpf")]
    [StringLength(14)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Required]
    [Column("senha")]
    [StringLength(255)]
    [Unicode(false)]
    public string Senha { get; set; }

    [Required]
    [Column("perfil")]
    [StringLength(20)]
    [Unicode(false)]
    public string Perfil { get; set; }
}